### PR TITLE
Fix text overflow on various components

### LINKED ISSUE #82: Design: too long text gets outside the square

### PR DESCRIPTION
**Pull request by sebastto**
Closes #82

Added css property `overflow-wrap: anywhere` to components with overflow issues for long single worded text strings

Before:
Skjermbilde 2021-09-27 kl  10 23 11

After:
Skjermbilde 2021-09-27 kl  10 58 24

### CODE REVIEW

**Comment by LERoise** [comment]
Would it not be a better solution to crop it with "This is my foobar ev..." so that the styling of the other boxes wont be unnecessarily tall ?

File: src/pages/EventPage/styled.ts [hunk 1]
```diff
@@ -2,6 +2,10 @@ import styled from 'styled-components';
 
 import { usingTypography, usingColors } from 'src/hooks/theme';
 
+export const EventHeader = styled.h1`
+  overflow-wrap: break-word;
```
Comment (sondregs) [inline src/pages/EventPage/styled.ts:6]:
```suggestion
  overflow-wrap: anywhere;
```

**Review by sondregs — APPROVED** [review]
LGTM
